// System-wide constants for LegacyVault

const ROLES = {
  OWNER: "owner",
  EXECUTOR: "executor",
  BENEFICIARY: "beneficiary",
  VERIFIER: "verifier",
  ADMIN: "admin",
};

const VAULT_STATUS = {
  ACTIVE: "ACTIVE",
  GRACE_PERIOD: "GRACE_PERIOD",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  UNLOCKED: "UNLOCKED",
  CLOSED: "CLOSED",
};

const ASSET_CATEGORY = {
  BANK_ACCOUNT: "BANK_ACCOUNT",
  CRYPTO_WALLET: "CRYPTO_WALLET",
  SOCIAL_MEDIA: "SOCIAL_MEDIA",
  LEGAL_DOCUMENT: "LEGAL_DOCUMENT",
};

const CLAIM_STATUS = {
  UNCLAIMED: "UNCLAIMED",
  NOTIFIED: "NOTIFIED",
  KYC_VERIFIED: "KYC_VERIFIED",
  DOWNLOADED: "DOWNLOADED",
  CONFIRMED: "CONFIRMED",
};

const VERIFICATION_STATUS = {
  SUBMITTED: "SUBMITTED",
  IN_REVIEW: "IN_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const EXECUTOR_STATUS = {
  ACTIVE: "ACTIVE",
  REVOKED: "REVOKED",
};

const AUDIT_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  VAULT_CREATED: "VAULT_CREATED",
  VAULT_UPDATED: "VAULT_UPDATED",
  VAULT_DELETED: "VAULT_DELETED",
  ASSET_CREATED: "ASSET_CREATED",
  ASSET_UPDATED: "ASSET_UPDATED",
  ASSET_DELETED: "ASSET_DELETED",
  HEARTBEAT_RESET: "HEARTBEAT_RESET",
  DMS_PING_SENT: "DMS_PING_SENT",
  DMS_GRACE_TRIGGERED: "DMS_GRACE_TRIGGERED",
  DMS_ESCALATED: "DMS_ESCALATED",
  EXECUTOR_ASSIGNED: "EXECUTOR_ASSIGNED",
  EXECUTOR_REVOKED: "EXECUTOR_REVOKED",
  VERIFICATION_SUBMITTED: "VERIFICATION_SUBMITTED",
  VERIFICATION_APPROVED: "VERIFICATION_APPROVED",
  VERIFICATION_REJECTED: "VERIFICATION_REJECTED",
  VAULT_UNLOCKED: "VAULT_UNLOCKED",
  VAULT_CLOSED: "VAULT_CLOSED",
  BENEFICIARY_NOTIFIED: "BENEFICIARY_NOTIFIED",
  KYC_SUBMITTED: "KYC_SUBMITTED",
  KYC_APPROVED: "KYC_APPROVED",
  ASSET_CLAIMED: "ASSET_CLAIMED",
  ASSET_CONFIRMED: "ASSET_CONFIRMED",
  ADMIN_USER_LOCKED: "ADMIN_USER_LOCKED",
  ADMIN_USER_UNLOCKED: "ADMIN_USER_UNLOCKED",
  FILE_UPLOADED: "FILE_UPLOADED",
  FILE_DOWNLOADED: "FILE_DOWNLOADED",
};

// DMS defaults
const DMS_DEFAULTS = {
  CHECK_INTERVAL_DAYS: 30,
  GRACE_PERIOD_DAYS: 14,
  // Warning schedule within grace period (days after T_check expires)
  WARNING_DAYS: [1, 7, 12],
};

module.exports = {
  ROLES,
  VAULT_STATUS,
  ASSET_CATEGORY,
  CLAIM_STATUS,
  VERIFICATION_STATUS,
  EXECUTOR_STATUS,
  AUDIT_ACTIONS,
  DMS_DEFAULTS,
};
